name: CI

on:
  push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 
      - name: yarn install
        run: yarn install
      - name: eslint review
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: './**/*.js'
      - name: Run eslint
        run: yarn lint
      - name: Run Jest
        run: yarn jest
      - name: Show coverage in comments
        uses: romeovs/lcov-reporter-action@v0.2.17
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
